NIAD-574: Mock LDAP response
NHSDigital/spine-directory-service-api pull request #68
Opened 2020-09-08 14:38 UTC by bartek-sarul

## Summary
* Routine Change
* :exclamation: Breaking Change
* :robot: Operational or Infrastructure Change
* :sparkles: New Feature
* :warning: Potential issues that might be caused by this change

Add any other relevant notes or explanations here. **Remove this line if you have nothing to add.**

## Reviews Required
* [x] Dev
* [ ] Test
* [ ] Tech Author
* [ ] Product Owner

## Review Checklist
:information_source: This section is to be filled in by the **reviewer**.

* [ ] I have reviewed the changes in this PR and they fill all or part of the acceptance criteria of the ticket, and the code is in a mergeable state.
* [ ] If there were infrastructure, operational, or build changes, I have made sure there is sufficient evidence that the changes will work.
* [ ] I have ensured the changelog has been updated by the submitter, if necessary.

2020-09-08 15:45 UTC, michael-kainos requested changes
Can we add a short readme of how to use this with docker locally.

2020-09-09 10:34 UTC, michael-kainos requested changes

2020-09-09 10:34 UTC, michael-kainos commented on docker/sds-api/spine-directory-service/sds/sds-mock-ldap.md
> +- `SDS_MOCK_LDAP_RESPONSE` - turns the behaviour on and off (`"True"` / `"False"`)
can we add these mock specific variables to the docker-compose.yml with defaults or in a override yaml file?

2020-09-10 10:55 UTC, michael-kainos commented on docker/sds-api/spine-directory-service/sds/lookup/mock_data/sds_response.json
> +    "https://192.168.128.11/reliablemessaging/reliablerequest"
should we have ip address here?

2020-09-10 10:56 UTC, michael-kainos commented on docker/sds-api/spine-directory-service/sds/lookup/tests/test_routing_reliability.py
>      'nhsMHSEndPoint': ['https://vpn-client-1411.opentest.hscic.gov.uk/'],
is this safe here?

2020-09-14 14:51 UTC, Broom94 approved these changes

2020-09-16 08:39 UTC, Sourceless commented
Force merging due to build not reporting done to github

2020-09-16 08:39 UTC, merged